load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
  name = "array_test",
  size = "small",
  srcs = ["array_test.cc"],
  deps = [
      "@com_google_googletest//:gtest_main",
      "//:Array"
  ],
)